apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: eagle-gmd
data:
  index.html: |
    <html>
    <head>
        <title>Hello World</title>
    </head>
    <body>
        <h1>Hello, world!</h1>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: eagle-gmd
  annotations:
    "greymatter.io/inject-sidecar-to": "80"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
          items:
          - key: index.html
            path: index.html

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: eagle-gmd
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
