apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge
  namespace: gmdata
spec:
  replicas: 1
  selector:
    matchLabels:
      greymatter.io/cluster: gmdata-edge
  template:
    metadata:
      labels:
        greymatter.io/cluster: gmdata-edge
    spec:
      containers:
        - name: sidecar
          image: greymatter.jfrog.io/oci/greymatter-proxy:1.9.1-beta1
          imagePullPolicy: Always
          ports:
          - containerPort: 10809
            name: ingress
          - containerPort: 8082
            name: stats
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: XDS_CLUSTER
              value: gmdata-edge
            - name: ENVOY_ADMIN_LOG_PATH
              value: /dev/stdout
            - name: ENVOY_ADMIN_PORT
              value: "8002"
            - name: PROXY_DYNAMIC
              value: "true"
            - name: XDS_ZONE
              value: default-zone
            - name: XDS_HOST
              value: controlensemble.greymatter.svc.cluster.local
            - name: XDS_PORT
              value: "50000"
          volumeMounts:
          - mountPath: /etc/proxy/tls/edge
            name: edge-certs
            readOnly: true
      volumes:
      - name: edge-certs
        secret:
          secretName: greymatter-edge-ingress
          defaultMode: 420
          items:
          - key: server.crt
            path: server.crt
          - key: server.key
            path: server.key
          - key: ca.crt
            path: ca.crt
      imagePullSecrets:
      - name: greymatter-image-pull

---
apiVersion: v1
kind: Service
metadata:
  name: edge
  namespace: gmdata
spec:
  ports:
  - name: ingress
    port: 10809
    protocol: TCP
    targetPort: 10809
  selector:
    greymatter.io/cluster: gmdata-edge
  type: LoadBalancer

