apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-reference-pvc
  namespace: gmdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-reference-deployment
  namespace: gmdata
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          ports:
            - containerPort: 27017
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-reference-pvc
