apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmdata
  namespace: gmdata
  annotations:
    "greymatter.io/inject-sidecar-to": "8181"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmdata
  template:
    metadata:
      labels:
        app: gmdata
    spec:
      imagePullSecrets:
      - name: greymatter-image-pull
      containers:
      - name: gmdata
        image: greymatter.jfrog.io/internal-oci/gm-data:latest
        ports:
        - containerPort: 8181
        env:
        - name: LESS_CHATTY_INFO
          value: "true"
        - name: CLIENT_JWT_ENDPOINT_ADDRESS
          value: "127.0.0.1"
        - name: CLIENT_JWT_ENDPOINT_PORT
          value: "10811"
        - name: CLIENT_JWT_ENDPOINT_PREFIX
          value: "/jwt"
        - name: JWT_API_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-keys
              key: jwtAPI.key.b64
        - name: JWT_PUB
          valueFrom:
            secretKeyRef:
              name: jwt-keys
              key: jwtES512.key.pub.b64
        - name: CLIENT_PREFIX
          value: ""
        - name: CLIENT_USE_TLS
          value: "false"
        - name: CLIENT_HOST
          value: "localhost"
        - name: CLIENT_PORT
          value: "8181"
        - name: GMDATA_NAMESPACE
          value: "world"
        - name: GMDATA_NAMESPACE_USERFIELD
          value: "email"
        - name: MASTERKEY
          valueFrom:
            secretKeyRef:
              name: gmdata-masterkey
              key: masterkey
        - name: FILE_BUCKET
          value: "decipherers"
        - name: FILE_PARTITION
          value: "gmdatax"
        - name: USES3
          value: "false"
        - name: MONGOHOST
          value: "127.0.0.1:27017"
        - name: MONGODB
          value: "chili"
        - name: KAFKA_PEERS
          value: "127.0.0.1:9092"
        - name: KAFKA_TOPIC_READ
          value: "gmdatax-audit"
        - name: KAFKA_TOPIC_UPDATE
          value: "gmdatax-replicationlog"
        volumeMounts:
        - name: gmdata-storage
          mountPath: /buckets
      volumes:
      - name: gmdata-storage
        persistentVolumeClaim:
          claimName: gmdata-pvc
           
