apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gmdata-pvc
  namespace: gmdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: "local-path" 

