apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-security
  namespace: gmdata
  annotations:
    "greymatter.io/inject-sidecar-to": "8080"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-security
  template:
    metadata:
      labels:
        app: jwt-security
    spec:
      imagePullSecrets:
      - name: greymatter-image-pull
      containers:
      - name: jwt-security
        image: greymatter.jfrog.io/internal-oci/gm-jwt-security:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        # This is the public key that users of this JWT must recognize
        - name: TOKEN_EXP_TIME
          value: "30000"
        # Don't use Redis. It causes problems, especially because it writes plaintext to the network without a TCP tunnel, and isn't necessary.
        - name: REDIS_HOST
          value: ""
        - name: ENABLE_TLS
          value: "false"
        - name: ZEROLOG_LEVEL
          value: debug
        # The secret required to use this service. It has to be a b64 value for some reason.
        - name: JWT_API_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-keys
              key: jwtAPI.key
        volumeMounts:
        - mountPath: /gm-jwt-security/etc
          name: users-json
          readOnly: true
        volumeMounts:
        - mountPath: /gm-jwt-security/certs
          name: jwt-keys
          readOnly: true
      volumes:
      - name: users-json
        secret:
          secretName: users-json
          defaultMode: 420
          items:
          - key: users.json
            path: users.json
      volumes:
      - name: jwt-keys
        secret:
          secretName: jwt-keys
          defaultMode: 420
          items:
          - key: jwtES512.key
            path: jwtESt12.key
          - key: jwtES512.key.pub
            path: jwtESt12.key.pub
          - key: jwtAPI.key
            path: jwtAPI.key

