apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: gmdata
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
---
apiVersion: apps/v1
kind: StatefuleSet
metadata:
  name: kafka
  namespace: gmdata
  annotations:
    "greymatter.io/inject-sidecar-to": "9092"
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.12-2.2.0
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk:2181
        - name: KAFKA_CREATE_TOPICS
          value: gmdatax-audit:1:1,gmdatax-replicationlog:1:1

