apiVersion: v1
kind: Service
metadata:
  name: zk
  namespace: gmdata
spec:
  selector:
    app: zk
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk
  namespace: gmdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
      - name: zk
        image: wurstmeister/zookeeper:latest
        ports:
        - containerPort: 2181

