apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  namespace: gmdata
  annotations:
    "greymatter.io/inject-sidecar-to": "2181"
spec:
  serviceName: zk
  replicas: 1
  selector:
    matchLabels:
      app: zk
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
      - name: zk
        image: wurstmeister/zookeeper:latest
        ports:
        - containerPort: 2181
        volumeMounts:
        - name: zk-storage
          mountPath: /opt/zookeeper-3.4.13/data
      volumes:
      - name: zk-storage
        persistentVolumeClaim:
          claimName: zk-pvc
